# Local as in no workload manager. Think about a workstation where everyone runs naked in the lobby.

cores: 1 # # This is just to force it to spawn only one process at a time. We're using the pipeline to generate the wanted setups for combinations of threads and samples -- Not to run things in parallel.

#software-deployment-method: conda
use-conda: true
conda-frontend: mamba

rerun-triggers: "mtime" # Only rerun on changes in modification time. Not on code hash changes.


